<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.392">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Some ideas for exploring missing data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="readme_files/libs/clipboard/clipboard.min.js"></script>
<script src="readme_files/libs/quarto-html/quarto.js"></script>
<script src="readme_files/libs/quarto-html/popper.min.js"></script>
<script src="readme_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="readme_files/libs/quarto-html/anchor.min.js"></script>
<link href="readme_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="readme_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="readme_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="readme_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="readme_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="readme.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Some ideas for exploring missing data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Nicholas Tierney</p>
<p>Infectious Disease Ecology and Modelling group</p>
<p>Telethon Kids Institute, Perth, WA, Australia</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visdat)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>When you do data analysis, you come across missing data. Because I felt so frustrated by how hard it was to handle and wrangle missing data, I wanted to make it easier. In my endeavours I have written two R packages, <code>visdat</code> and <code>naniar</code>, for exploring missing data, and several papers on the topic.</p>
<p>The goal of this article is to share some condensed ideas on exploring missing data, using <code>naniar</code>, and <code>visdat</code>. To that end, we will focus on four questions.</p>
<ol type="1">
<li>How do we start looking at missing data?</li>
<li>How do we explore missingness in variables?</li>
<li>How do we explore missingness relationships?</li>
<li>How do we explore imputed values?</li>
</ol>
<p>But first, let’s introduce ourselves to the data.</p>
</section>
<section id="the-data" class="level1">
<h1>The data</h1>
<p>The data used for this paper is measurements of rodents in Kansas, from <span class="citation" data-cites="hope2023">Hope (<a href="#ref-hope2023" role="doc-biblioref">2023</a>)</span>. The use of this data is inspired by Allison Horst’s “Exploring missing values in naniar” <a href="https://allisonhorst.shinyapps.io/missingexplorer/">shiny application</a>. In this paper we use a different, larger set of the data. For information on the metadata of the paper see <a href="http://lter.konza.ksu.edu/content/csm08-small-mammal-host-parasite-sampling-data-16-linear-trapping-transects-located-8-lter">here</a>. The data set provides various biometric length and weight measurements, for four species of rodents: the Eastern woodrat, Prairie vole, Western harvest mouse, and Deer mouse. Table <a href="#tbl-rodents-slice" class="quarto-xref">Table&nbsp;1</a> shows a snapshot of 6 rows of the data, including some of the missingness.</p>
<div class="cell">
<div id="tbl-rodents-slice" class="cell anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="table quarto-float-caption quarto-float-tbl" id="tbl-rodents-slice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The rodents dataset, containing measurements of various rodents, including: total length - from tail to nose, tail length, hind foot length, ear length, and weight. Each row represents a measurement of a given species of roden at a particular date. There are missing values.
</figcaption>
<div aria-describedby="tbl-rodents-slice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">date</th>
<th style="text-align: left;">species</th>
<th style="text-align: right;">total_length</th>
<th style="text-align: right;">tail_length</th>
<th style="text-align: right;">hind_foot_length</th>
<th style="text-align: right;">ear_length</th>
<th style="text-align: right;">weight</th>
<th style="text-align: left;">sex</th>
<th style="text-align: left;">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">prairie vole</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">30.0</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">A</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">deer mouse</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">17.5</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">A</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">western harvest mouse</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">N</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">western harvest mouse</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">N</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">prairie vole</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">N</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016-07-21</td>
<td style="text-align: left;">prairie vole</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">18.0</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Juv</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="how-do-we-start-looking-at-missing-data" class="level1">
<h1>How do we start looking at missing data?</h1>
<p>To get an overview of the missing data, we can use the <code>visdat</code> package <span class="citation" data-cites="visdat">(<a href="#ref-visdat" role="doc-biblioref">N. Tierney 2017</a>)</span>, which was inspired by the work in <a href="https://setosa.io/blog/2014/08/03/csv-fingerprints/"><code>csv-fingerprint</code></a>, and functions like <code>missmap</code>, from <code>Amelia</code> <span class="citation" data-cites="amelia">(<a href="#ref-amelia" role="doc-biblioref">Honaker, King, and Blackwell 2011</a>)</span>. The key function for exploring missingness is <code>vis_miss()</code>, which visualises the missingness of a whole dataframe. <a href="#fig-vis-miss" class="quarto-xref">Figure&nbsp;1</a> gives an example where it displays the data as missing, or not missing, and provides information on the amount of missings in each column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-vis-miss" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vis-miss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-vis-miss-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-vis-miss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: An overview of missing data in the rodents dataset. The x axis shows the variables of the data, along with the amount of missingness in that variable, and the y axis shows the rows. Each cell represents the missingness of a datum. The overall missingness is given in a percentage below in the legend. We learn that there is nearly 29% missing data overall, the missing data occurs in total_length, tail_length, hind_foot_length, ear_length, weight, and age.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We learn there is nearly 29% missing data overall, the missing data occurs in total_length, tail_length, hind_foot_length, ear_length, weight, and age, and mostly in total length and ear_length.</p>
<section id="exploring-subgroups-using-facetting-in-visdat" class="level2">
<h2 class="anchored" data-anchor-id="exploring-subgroups-using-facetting-in-visdat">Exploring subgroups: Using facetting in visdat</h2>
<p>To see this plot split up by species, we can split up the <code>vis_miss</code> plots into several facetted plots via the <code>facet</code> argument. For example, in <a href="#fig-vis-miss-facet" class="quarto-xref">Figure&nbsp;2</a> we facet by the <code>species</code> variable. Visually, it appears that the missingness occurs in each species at roughly the same rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(rodents, <span class="at">facet =</span> species) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-vis-miss-facet" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vis-miss-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-vis-miss-facet-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-vis-miss-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: An further overview of missing data in the rodents dataset. Similar to the previous graphic, we now present a facetted series of sub plots, one for each species. We learn from this that the missingness seems to be the same across each species
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are other functions in the visdat package that focus on other types of data, for example, <code>vis_value()</code>, <code>vis_binary()</code>, and <code>vis_compare()</code>. To read more about the functions available in <code>visdat</code> see the vignette <a href="https://CRAN.R-project.org/package=visdat/vignettes/using_visdat.html">“Using visdat”</a>.</p>
</section>
</section>
<section id="how-do-we-explore-missingness-in-variables" class="level1">
<h1>How do we explore missingness in variables?</h1>
<p>The <code>visdat</code> package provides overviews of data, whereas <code>naniar</code> provides a more comprehensive set of tools for missing data.</p>
<section id="numerical-summaries-of-missing-values" class="level2">
<h2 class="anchored" data-anchor-id="numerical-summaries-of-missing-values">Numerical summaries of missing values</h2>
<p>Two convenient counters of complete values and missings are <code>n_miss()</code> and <code>n_complete()</code>. These work on both data frames and vectors, similar to <code>dplyr::n_distinct()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">n_distinct</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 617</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">n_distinct</span>(rodents<span class="sc">$</span>tail_length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 96</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_miss</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_miss</span>(rodents<span class="sc">$</span>tail_length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 245</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_complete</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4944</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_complete</span>(rodents<span class="sc">$</span>tail_length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 528</code></pre>
</div>
</div>
<p><code>prop_miss_case</code> and <code>pct_miss_case</code> return numeric value describing the proportion or percent of missing values in the dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_miss_case</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7477361</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pct_miss_case</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 74.77361</code></pre>
</div>
</div>
<p>Similar to <code>pct_miss_case()</code>, <code>prop_miss_case()</code>, <code>pct_miss_var()</code> and <code>prop_miss_var()</code> returns the percent and proportion of variables that contain a missing value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_miss_var</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6666667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pct_miss_var</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.66667</code></pre>
</div>
</div>
<p>The syntax for the other numerical summaries in <code>naniar</code> are <code>miss_</code>, and then <code>case</code>, or <code>var</code> to refer to cases or variables. There are then <code>summary</code>, <code>table</code> suffixes.</p>
<p><code>miss_case_summary()</code> returns a numeric value that describes the number of missings in a given case (aka row), the percent of missings in that row.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_case_summary</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 773 × 3
    case n_miss pct_miss
   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
 1    63      6     66.7
 2    74      6     66.7
 3    77      6     66.7
 4    78      6     66.7
 5    79      6     66.7
 6    91      6     66.7
 7    94      6     66.7
 8    95      6     66.7
 9    98      6     66.7
10   100      6     66.7
# ℹ 763 more rows</code></pre>
</div>
</div>
<p><code>miss_case_table()</code> tabulates the number of missing values in a case / row. Below, this shows the number of missings in a case:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_case_table</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  n_miss_in_case n_cases pct_cases
           &lt;int&gt;   &lt;int&gt;     &lt;dbl&gt;
1              0     195     25.2 
2              1      48      6.21
3              2     277     35.8 
4              3      10      1.29
5              4      14      1.81
6              5      49      6.34
7              6     180     23.3 </code></pre>
</div>
</div>
<p>We can interpret this output as follows:</p>
<ul>
<li>There are 195 cases with 0 missings, which comprises about 25% of the data.</li>
<li>There are 48 cases with 1 missing, these make up 6% of the data.</li>
<li>There are 277 cases with 2 missing, these make up 35% of the data.</li>
<li>And so on.</li>
</ul>
<p><code>miss_var_summary()</code> then returns the number of missing values in a variable, and the percent missing in that variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  variable         n_miss pct_miss
  &lt;chr&gt;             &lt;int&gt;    &lt;dbl&gt;
1 total_length        569     73.6
2 ear_length          530     68.6
3 tail_length         245     31.7
4 hind_foot_length    243     31.4
5 weight              237     30.7
6 age                 189     24.5
7 date                  0      0  
8 species               0      0  
9 sex                   0      0  </code></pre>
</div>
</div>
<p>Finally, <code>miss_var_table()</code>. This describes the number of missings in a variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_table</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  n_miss_in_var n_vars pct_vars
          &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
1             0      3     33.3
2           189      1     11.1
3           237      1     11.1
4           243      1     11.1
5           245      1     11.1
6           530      1     11.1
7           569      1     11.1</code></pre>
</div>
</div>
<p>We can interpret this as:</p>
<ul>
<li>There are 3 variables with 0 missings, comprising 33% of variables in the dataset.</li>
<li>There are in the remaining variables similar patterns of missings, but not the exact same number of missing values.</li>
</ul>
</section>
<section id="visualise-missingness-in-variables" class="level2">
<h2 class="anchored" data-anchor-id="visualise-missingness-in-variables">Visualise missingness in variables</h2>
<p>To specifically focus on the number or proportion of missings in each variable, we can use <code>gg_miss_var()</code>, as seen in <a href="#fig-gg-miss-var" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gg-miss-var" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gg-miss-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-gg-miss-var-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-gg-miss-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Number of missing values for each variable. The x axis shows the number of missings, and the y axis shows each variable. We learn total length, and ear length have the most missing values, followed by tail length, hind foot length, weight, and age.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This displays the number of missing values in each variable. We learn similar information to <a href="#fig-vis-miss" class="quarto-xref">Figure&nbsp;1</a>: total length, and ear length have the most missing values, followed by tail length, hind foot length, weight, and age. Just like with <code>vis_miss()</code>, we can add in facets in these plots, via the <code>facet</code> argument, see <a href="#fig-gg-miss-var-facet" class="quarto-xref">Figure&nbsp;4</a>. We learn again, that the species have similar amounts of missing data in their variables. Sometimes it is useful to confirms the same piece of information!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(rodents, <span class="at">facet =</span> species, <span class="at">show_pct =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gg-miss-var-facet" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gg-miss-var-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-gg-miss-var-facet-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-gg-miss-var-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Similar to the above plot but one subplot for each species. We learn that the missingness pattern is pretty similar for each species. We normalise using <code>show_pct = TRUE</code> as there are different numbers of observations in each species.
</figcaption>
</figure>
</div>
</div>
</div>
<p>It feels like there are several patterns with the missingness - some variables tend to go missing at the same time. To explore these patterns we can use <code>gg_miss_upset()</code>, which produces an “upset” plot <span class="citation" data-cites="Conway2017">(<a href="#ref-Conway2017" role="doc-biblioref">Conway, Lex, and Gehlenborg 2017</a>)</span> of the intersecting sets of missingness. This can be thought of as a generalised way to visualise intersecting venn diagrams.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_upset</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gg-miss-upset" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gg-miss-upset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-gg-miss-upset-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-gg-miss-upset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: An upset plot of 7 sets of missingness in the rodents data displaying a more nuanced depiction of the patterns of missingness in the data. The number of missings in each variable is seen on the bottom left bar plot. The bottom panel shows the different sets of co-occuring missingness. For example, the bottom left two dots show ear length and total length going missing together - corresponding to the bar plot above it, showing 278 missings. We learn that there are two dominant sets of missingness, where ear length and total length go missing, and then weight hind foot length, tail length, ear length and total length being missing.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are more visualisations available in <code>naniar</code> (each starting with <code>gg_miss_</code>) - you can see these in the <a href="https://cran.r-project.org/package=naniar/vignettes/naniar-visualisation.html">“Gallery of Missing Data Visualisations” vignette</a>. Most plots created with the <code>gg_miss</code> family all have a basic theme (except for <code>gg_miss_upset()</code>), but you can customise them by adding components like a standard ggplot object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(rodents) <span class="sc">+</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Number of missing observations"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It is also worth noting that for every visualisation of missing data in <code>naniar</code>, there is an accompanying function to extract the data used in the plot. This is important as the plot should not return a dataframe - but we want to make the data available for use by the user so it isn’t locked into a plot.</p>
<p>You can find these summary plots below, with <code>miss_var_summary()</code> providing the dataframe that <code>gg_miss_var()</code> is based on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  variable         n_miss pct_miss
  &lt;chr&gt;             &lt;int&gt;    &lt;dbl&gt;
1 total_length        569     73.6
2 ear_length          530     68.6
3 tail_length         245     31.7
4 hind_foot_length    243     31.4
5 weight              237     30.7
6 age                 189     24.5
7 date                  0      0  
8 species               0      0  
9 sex                   0      0  </code></pre>
</div>
</div>
<p>Which also works with <code>group_by()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>rodents <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">miss_var_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly, there is a <code>data_vis_miss()</code> function in the <code>visdat</code> package, which returns the data in the format that this visualisation requires.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data_vis_miss</span>(rodents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The aim of these is to provide the data required to make these visualisations, so if people want to create their own more customised versions of <code>vis_miss()</code> or <code>gg_miss_var()</code> then they can do that.</p>
</section>
</section>
<section id="how-to-explore-missingness-relationships" class="level1">
<h1>How to explore missingness relationships?</h1>
<p>We can identify key missing variables using <code>vis_miss()</code>, <code>gg_miss_var()</code>, and <code>gg_miss_upset()</code>, but for further exploration, we need to explore the relationship amongst the variables in this data:</p>
<ul>
<li>date</li>
<li>species</li>
<li>total_length</li>
<li>tail_length</li>
<li>hind_foot_length</li>
<li>ear_length</li>
<li>weight</li>
<li>sex</li>
<li>age</li>
</ul>
<section id="exploring-using-bivariate-plots" class="level2">
<h2 class="anchored" data-anchor-id="exploring-using-bivariate-plots">Exploring using bivariate plots</h2>
<p>Let’s say that we want to explore the relationship between tail length and ear length. <a href="#fig-example-geom-point" class="quarto-xref">Figure&nbsp;6</a> shows a scatter plot of tail length and ear length.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rodents, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ear_length, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> tail_length)) <span class="sc">+</span> </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-example-geom-point" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-example-geom-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-example-geom-point-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-example-geom-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Plot of ear length against tail length. Ear length is on the X axis and tail length is on the Y axis. We learn that there is a reasonable positive correlation of tail length and ear length.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The problem with this is ggplot does not handle missings removes the missing values. This makes them hard to explore. We can impute missings with values 10% lower than the minimum value in that variable, which puts these values in a margin area on the graphic. This method comes from <a href="https://en.wikipedia.org/wiki/GGobi"><code>ggobi</code></a> <span class="citation" data-cites="Cook2007">(<a href="#ref-Cook2007" role="doc-biblioref">Cook and Swayne 2007</a>)</span>, and <a href="http://www.rosuda.org/MANET/"><code>manet</code></a> <span class="citation" data-cites="Unwin1996">(<a href="#ref-Unwin1996" role="doc-biblioref">Unwin et al. 1996</a>)</span>.</p>
<p>This imputation is wrapped up in the <code>geom_miss_point()</code> ggplot2 geom. <a href="#fig-geom-miss-point" class="quarto-xref">Figure&nbsp;7</a> illustrates this by exploring the relationship between tail length and ear length from the rodents dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rodents, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ear_length, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> tail_length)) <span class="sc">+</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_miss_point</span>() <span class="sc">+</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-geom-miss-point" class="quarto-figure quarto-figure-center anchored" width="384">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-geom-miss-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-geom-miss-point-1.png" class="img-fluid figure-img" width="384">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-geom-miss-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Improved plot of tail length against ear length, we can now see the missing values are imputed 10% below the minimum value. The green dots on the Y axis represent tail_length values that have missing ear_length. There aren’t any missing values on the X axis, because there aren’t times where tail length is missing when ear length is missing. The row of dots in the bottom left corner are missing for both tail length and ear length
</figcaption>
</figure>
</div>
</div>
</div>
<p>Being a proper ggplot geom, it supports all of the standard features of ggplot2, such as <strong>facets</strong> and <strong>themes</strong>. See <a href="#fig-ggmissing-facet" class="quarto-xref">Figure&nbsp;8</a> for an example with faceting by month and a custom theme.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rodents, </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ear_length, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> tail_length)) <span class="sc">+</span> </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_miss_point</span>() <span class="sc">+</span> </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>species) <span class="sc">+</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dark</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ggmissing-facet" class="quarto-figure quarto-figure-center anchored" width="576">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ggmissing-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-ggmissing-facet-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-ggmissing-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: A faceted version of the improved tail length against ear length plot where each species is split out into its own subplot.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="exploring-using-modelling" class="level2">
<h2 class="anchored" data-anchor-id="exploring-using-modelling">Exploring using modelling</h2>
<p>As evidenced by <a href="#fig-gg-miss-upset" class="quarto-xref">Figure&nbsp;5</a>, there is a structure in the missingness in the rodents data. We can perform some basic clustering on the missingness and then and learn which variables and their values predict these missingness groups using decision trees <span class="citation" data-cites="Tierney2015 Barnett2017">(<a href="#ref-Tierney2015" role="doc-biblioref">N. J. Tierney et al. 2015</a>; <a href="#ref-Barnett2017" role="doc-biblioref">Barnett et al. 2017</a>)</span>. We start by adding missingness clusters, choosing four based on <a href="#fig-gg-miss-upset" class="quarto-xref">Figure&nbsp;5</a>. We encourage exploring different numbers of clusters. We can then confirm this pattern using visualisations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>rodents_miss_clust <span class="ot">&lt;-</span> rodents <span class="sc">%&gt;%</span> <span class="fu">add_miss_cluster</span>(<span class="at">n_clusters =</span> <span class="dv">4</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(rodents_miss_clust, <span class="at">facet =</span> miss_cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="readme_files/figure-html/gg-miss-var-cluster-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Number of missings for each variable for each cluster. We see clear patterns emerge where there are two variables missing in cluster two, six variables missing in cluster three, and not as many missings in clusters one and four.</figcaption>
</figure>
</div>
</div>
</div>
<p>We use the R package <code>rpart</code> <span class="citation" data-cites="rpart">(<a href="#ref-rpart" role="doc-biblioref">Therneau and Atkinson 2023</a>)</span> to fit a classification and regression tree (CART) to the data using all variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>rodent_miss_cart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(miss_cluster) <span class="sc">~</span> ., </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> rodents_miss_clust</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Variable importance scores (<a href="#tbl-var-imp" class="quarto-xref">Table&nbsp;2</a>) reveal the most important variables for predicting missingness cluster are date and sex.</p>
<div class="cell">
<div id="tbl-var-imp" class="cell anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="table quarto-float-caption quarto-float-tbl" id="tbl-var-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Variable importance scores for predicting missingness cluster. The most important variables are date and sex.
</figcaption>
<div aria-describedby="tbl-var-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: right;">importance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">date</td>
<td style="text-align: right;">221.387697</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">167.959712</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hind_foot_length</td>
<td style="text-align: right;">20.283431</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">15.078286</td>
</tr>
<tr class="odd">
<td style="text-align: left;">species</td>
<td style="text-align: right;">10.671966</td>
</tr>
<tr class="even">
<td style="text-align: left;">tail_length</td>
<td style="text-align: right;">7.373253</td>
</tr>
<tr class="odd">
<td style="text-align: left;">weight</td>
<td style="text-align: right;">5.177268</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>To better understand these relationships, we would recommend exploring using partial dependence plots using packages such as <code>vip</code> <span class="citation" data-cites="vip">(<a href="#ref-vip" role="doc-biblioref">Greenwell and Boehmke 2020</a>)</span> and other decision tree plots using <code>rpart.plot</code> <span class="citation" data-cites="rpart.plot">(<a href="#ref-rpart.plot" role="doc-biblioref">Milborrow 2022</a>)</span>.</p>
</section>
</section>
<section id="how-do-we-explore-imputed-values" class="level1">
<h1>How do we explore imputed values?</h1>
<p>The <a href="https://cran.r-project.org/package=simputation"><code>simputation</code></a> package provides a nice interface to imputation. We will impute values for tail_length using the <code>impute_lm()</code> function, then visualise the data, as seen in <a href="#fig-simpute-invisible" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(simputation)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>rodents <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_lm</span>(tail_length <span class="sc">~</span> species <span class="sc">+</span> age) <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weight,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> tail_length)) <span class="sc">+</span> </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 237 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-simpute-invisible" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simpute-invisible-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-simpute-invisible-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-simpute-invisible-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Imputed values are not visible. A plot of tail length by weight. The Imputed tail length values are not visible because we have no way to identify them in the data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We don’t get any warnings regarding missing observations - because they are all imputed! However this comes at a cost: we don’t know where the imputations are - they are now sort of invisible.</p>
<p>We can track a copy of the missing data locations by using the function <code>nabular()</code>, which binds another dataset to the current one which notes the locations of the missing data. “Nabular” data is a really important idea in <code>naniar</code>, but to keep it brief, for each column with missing values, a new column is created to help identify misingness. For example, a new column called <code>ear_length_NA</code> is created:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nabular</span>(rodents) <span class="sc">|&gt;</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">"ear_length"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  ear_length ear_length_NA
       &lt;dbl&gt; &lt;fct&gt;        
1         39 !NA          
2         18 !NA          
3         17 !NA          
4         21 !NA          
5         19 !NA          
6         19 !NA          </code></pre>
</div>
</div>
<p>The key takeaway here is there is now a copy of the data bound to it, with each column ending in <code>_NA</code>, and the values either being “NA” for missing, or “!NA” for not missing. For more details on the ideas underlying this, and the benefits, we recommend reading our paper, “Expanding Tidy Data Principles to Facilitate Missing Data Exploration, Visualization and Assessment of Imputations” <span class="citation" data-cites="Tierney2023">(<a href="#ref-Tierney2023" role="doc-biblioref">N. Tierney and Cook 2023</a>)</span>.</p>
<p>Using the shadow matrix to keep track of where the missings are, you can actually keep track of the imputations, colouring by what was previously missing in tail_length. For example, let’s create the nabular data, then impute the data using a random forst, and plot it in <a href="#fig-simpute-visible-lm" class="quarto-xref">Figure&nbsp;10</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>rodents_nabular <span class="ot">&lt;-</span> rodents <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nabular</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>rodents_lm_tail_imputed <span class="ot">&lt;-</span> rodents_nabular <span class="sc">%&gt;%</span> </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_lm</span>(tail_length <span class="sc">~</span> species <span class="sc">+</span> date) <span class="sc">%&gt;%</span> </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_lm</span>(weight <span class="sc">~</span> tail_length <span class="sc">+</span> species <span class="sc">+</span> date)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rodents_lm_tail_imputed,</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>         <span class="fu">aes</span>(<span class="at">x =</span> weight,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> tail_length,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> tail_length_NA)) <span class="sc">+</span> </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-simpute-visible-lm" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simpute-visible-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-simpute-visible-lm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-simpute-visible-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Linear model imputed values of tail length in a scatterplot of tail length vs weight. Weight is on the X axis and tail_length is on the Y axis, and the points are coloured by whether they are imputed - ‘NA’ indicates a previously missing value that has been imputed. We can see where imputations are added, but they are very concentrated
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>simputation</code> package has a nice option to add residual noise to the imputations - in this case we can add some normal noise to the observations, where the residuals are draws with replacement from the model residuals. This gives us much greater variation in the imputations. For comparison to other naive approaches, we will also add mean imputation for comparison</p>
<p>Importantly, we can actually compare the two methods as below. This first imputes the data using the residual method, then rowbinds the two datasets together, creating a column called “imputation_type”, which records which type of imputation was used, either “add_residual” or “no_residual”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>rodents_lm_tail_imputed_res <span class="ot">&lt;-</span> rodents_nabular <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_lm</span>(tail_length <span class="sc">~</span> species <span class="sc">+</span> date, <span class="at">add_residual =</span> <span class="st">"observed"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_lm</span>(weight <span class="sc">~</span> tail_length <span class="sc">+</span> species <span class="sc">+</span> date, <span class="at">add_residual =</span> <span class="st">"observed"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>rodents_mean_imputed <span class="ot">&lt;-</span> rodents <span class="sc">%&gt;%</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nabular</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">impute_mean_all</span>()</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>rodents_imputed_comparison <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">add_residual =</span> rodents_lm_tail_imputed_res,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_residual =</span> rodents_lm_tail_imputed,</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_imp =</span> rodents_mean_imputed,</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">.id =</span> <span class="st">"imputation_type"</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>rodents_imputed_comparison</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,319 × 19
   imputation_type date       species  total_length tail_length hind_foot_length
   &lt;chr&gt;           &lt;date&gt;     &lt;chr&gt;           &lt;dbl&gt;       &lt;dbl&gt;            &lt;dbl&gt;
 1 add_residual    2016-07-12 eastern…          360         165               28
 2 add_residual    2016-07-12 prairie…          123          32               12
 3 add_residual    2016-07-12 western…          138          69               15
 4 add_residual    2016-07-12 prairie…          149          35               13
 5 add_residual    2016-07-12 deer mo…          136          57               16
 6 add_residual    2016-07-12 deer mo…          169          55               15
 7 add_residual    2016-07-12 deer mo…          139          55               15
 8 add_residual    2016-07-12 deer mo…          136          57               14
 9 add_residual    2016-07-13 eastern…          331         136               27
10 add_residual    2016-07-13 eastern…          339         159               28
# ℹ 2,309 more rows
# ℹ 13 more variables: ear_length &lt;dbl&gt;, weight &lt;dbl&gt;, sex &lt;chr&gt;, age &lt;chr&gt;,
#   date_NA &lt;fct&gt;, species_NA &lt;fct&gt;, total_length_NA &lt;fct&gt;,
#   tail_length_NA &lt;fct&gt;, hind_foot_length_NA &lt;fct&gt;, ear_length_NA &lt;fct&gt;,
#   weight_NA &lt;fct&gt;, sex_NA &lt;fct&gt;, age_NA &lt;fct&gt;</code></pre>
</div>
</div>
<p>We can see see the two different imputation methods side by side in <a href="#fig-imputed-comparison" class="quarto-xref">Figure&nbsp;11</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rodents_imputed_comparison,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">aes</span>(<span class="at">x =</span> weight,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> tail_length,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> tail_length_NA)) <span class="sc">+</span> </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span> </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>imputation_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-imputed-comparison" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-imputed-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="readme_files/figure-html/fig-imputed-comparison-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-imputed-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Comparing imputation methods of tail length in a scatterplot of tail length vs weight. Weight is on the X axis and tail_length is on the Y axis, and the points are coloured by whether they are imputed - ‘NA’ indicates a previously missing value that has been imputed. We learn that mean imputation provides imputations that are not representative, linear models with no residuals are representative of the data but very concentrated, and adding residuals adds much more variation to your data.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this software corner we have demonstrated the use of the <code>visdat</code> and <code>naniar</code> R packages for exploring and understanding missing data.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Barnett2017" class="csl-entry" role="listitem">
Barnett, Adrian G., Paul McElwee, Andrea Nathan, Nicola W. Burton, and Gavin Turrell. 2017. <span>“Identifying Patterns of Item Missing Survey Data Using Latent Groups: An Observational Study.”</span> <em>BMJ Open</em> 7 (10): e017284. <a href="https://doi.org/10.1136/bmjopen-2017-017284">https://doi.org/10.1136/bmjopen-2017-017284</a>.
</div>
<div id="ref-Conway2017" class="csl-entry" role="listitem">
Conway, Jake R., Alexander Lex, and Nils Gehlenborg. 2017. <span>“<span>UpSetR</span>: An <span>R</span> Package for the Visualization of Intersecting Sets and Their Properties.”</span> <em>Bioinformatics (Oxford, England)</em> 33 (18): 2938–40. <a href="https://doi.org/10.1093/bioinformatics/btx364">https://doi.org/10.1093/bioinformatics/btx364</a>.
</div>
<div id="ref-Cook2007" class="csl-entry" role="listitem">
Cook, Dianne, and Deborah F. Swayne. 2007. <em>Interactive and <span>Dynamic</span> <span>Graphics</span> for <span>Data</span> <span>Analysis</span>: <span>With</span> and </em>. Use <span>R</span>! New York: Springer. <a href="https://doi.org/10.1007/978-0-387-71762-3">https://doi.org/10.1007/978-0-387-71762-3</a>.
</div>
<div id="ref-vip" class="csl-entry" role="listitem">
Greenwell, Brandon M., and Bradley C. Boehmke. 2020. <span>“Variable Importance Plots—an Introduction to the Vip Package.”</span> <em>The R Journal</em> 12 (1): 343–66. <a href="https://doi.org/10.32614/RJ-2020-013">https://doi.org/10.32614/RJ-2020-013</a>.
</div>
<div id="ref-amelia" class="csl-entry" role="listitem">
Honaker, James, Gary King, and Matthew Blackwell. 2011. <span>“<span>Amelia II</span>: A Program for Missing Data.”</span> <em>Journal of Statistical Software</em> 45 (1): 1–47. <a href="https://doi.org/10.18637/jss.v045.i07">https://doi.org/10.18637/jss.v045.i07</a>.
</div>
<div id="ref-hope2023" class="csl-entry" role="listitem">
Hope, Andrew. 2023. <span>“<span>CSM08</span> <span>Small</span> Mammal Host-Parasite Sampling Data for 16 Linear Trapping Transects Located in 8 <span>LTER</span> Burn Treatment Watersheds at <span>Konza</span> <span>Prairie</span>.”</span> Environmental Data Initiative. <a href="https://doi.org/10.6073/PASTA/F7BFB7226B093C817DC391C34A88B514">https://doi.org/10.6073/PASTA/F7BFB7226B093C817DC391C34A88B514</a>.
</div>
<div id="ref-rpart.plot" class="csl-entry" role="listitem">
Milborrow, Stephen. 2022. <em>Rpart.plot: Plot ’Rpart’ Models: An Enhanced Version of ’Plot.rpart’</em>. <a href="https://CRAN.R-project.org/package=rpart.plot">https://CRAN.R-project.org/package=rpart.plot</a>.
</div>
<div id="ref-rpart" class="csl-entry" role="listitem">
Therneau, Terry, and Beth Atkinson. 2023. <em>Rpart: Recursive Partitioning and Regression Trees</em>. <a href="https://CRAN.R-project.org/package=rpart">https://CRAN.R-project.org/package=rpart</a>.
</div>
<div id="ref-visdat" class="csl-entry" role="listitem">
Tierney, Nicholas. 2017. <span>“<span class="nocase">visdat</span>: Visualising Whole Data Frames.”</span> <em>The Journal of Open Source Software</em> 2 (16): 355. <a href="https://doi.org/10.21105/joss.00355">https://doi.org/10.21105/joss.00355</a>.
</div>
<div id="ref-Tierney2015" class="csl-entry" role="listitem">
Tierney, Nicholas J., Fiona A. Harden, Maurice J. Harden, and Kerrie L. Mengersen. 2015. <span>“Using Decision Trees to Understand Structure in Missing Data.”</span> <em>BMJ Open</em> 5 (6): e007450. <a href="https://doi.org/10.1136/bmjopen-2014-007450">https://doi.org/10.1136/bmjopen-2014-007450</a>.
</div>
<div id="ref-Tierney2023" class="csl-entry" role="listitem">
Tierney, Nicholas, and Dianne Cook. 2023. <span>“Expanding Tidy Data Principles to Facilitate Missing Data Exploration, Visualization and Assessment of Imputations.”</span> <em>Journal of Statistical Software</em> 105 (7): 1–31. <a href="https://doi.org/10.18637/jss.v105.i07">https://doi.org/10.18637/jss.v105.i07</a>.
</div>
<div id="ref-Unwin1996" class="csl-entry" role="listitem">
Unwin, Antony, George Hawkins, Heike Hofmann, and Bernd Siegl. 1996. <span>“Interactive <span>Graphics</span> for <span>Data</span> <span>Sets</span> with <span>Missing</span> <span>Values</span>—.”</span> <em>Journal of Computational and Graphical Statistics</em> 5 (2): 113–22. <a href="https://doi.org/10.1080/10618600.1996.10474700">https://doi.org/10.1080/10618600.1996.10474700</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>